# Generated by Django 2.2.16 on 2020-12-27 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='This name field is to identify easily each course by the users (in addition to its id number), its length is 30 alphanumerical characters as maximum,and this is mandatory', max_length=30, verbose_name="Classification's Name")),
                ('overview', models.CharField(help_text='This field is to give a brief overview about this classification in a maximum of 200 alphanumerical characters, and this is not mandatory', max_length=200, verbose_name="Classification's Overview")),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='This name field is to identify easily each course by the users (in addition to its id number), its length is 30 alphanumerical characters as maximum,and this is mandatory', max_length=30, verbose_name="Course's Name")),
                ('overview', models.CharField(help_text='This field is to give a brief overwiew about this course and its details in a maximum of 200 alphanumerical characters, and this is not mandatory', max_length=200, verbose_name="Course's Overview")),
                ('quota', models.IntegerField(default=0, help_text='The quota field defines the maximum number of students allowed in this course, but if this value is not set or is zero, the course will not have a mandatory limit of students')),
                ('course_type', models.ForeignKey(blank=True, help_text='This field indicates the classification of this course', null=True, on_delete=django.db.models.deletion.SET_NULL, to='UsersData.CourseType')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
